-- Substitui o catálogo de exercícios pelos novos GIFs enviados (pasta
-- /gif do projeto, processada e copiada pra public/exercicios/). Mantém só
-- o grupo Abdômen do catálogo antigo, que não tem equivalente na leva nova.
--
-- Remove template_exercises e session_sets que apontam pros exercícios
-- sendo descartados antes de apagar os exercícios em si (ambas as tabelas
-- referenciam exercises com on delete restrict).
delete from template_exercises
where exercise_id in (
  select id from exercises where grupo_muscular <> 'Abdômen'
);

delete from session_sets
where exercise_id in (
  select id from exercises where grupo_muscular <> 'Abdômen'
);

delete from exercises where grupo_muscular <> 'Abdômen';

insert into exercises (nome, grupo_muscular, gif_url) values
  ('Flexão de pulso neutra sentado com halteres', 'Antebraço', '/exercicios/flexao-de-pulso-neutra-sentado-com-halteres.gif'),
  ('Flexão de punho com cabo em um braço no chão', 'Antebraço', '/exercicios/flexao-de-punho-com-cabo-em-um-braco-no-chao.gif'),
  ('Flexão de punho com halteres', 'Antebraço', '/exercicios/flexao-de-punho-com-halteres.gif'),
  ('Flexão de punho reversa com anilha', 'Antebraço', '/exercicios/flexao-de-punho-reversa-com-anilha.gif'),
  ('Flexão de punho reversa com barra sobre um banco', 'Antebraço', '/exercicios/flexao-de-punho-reversa-com-barra-sobre-um-banco.gif'),
  ('Hand grip', 'Antebraço', '/exercicios/hand-grip.gif'),
  ('Rolinho de antebraço', 'Antebraço', '/exercicios/rolinho-de-antebraco.gif'),
  ('Rosca de dedo com barra', 'Antebraço', '/exercicios/rosca-de-dedo-com-barra.gif'),
  ('Rosca de dedos com halteres', 'Antebraço', '/exercicios/rosca-de-dedos-com-halteres.gif'),
  ('Rosca de punho com barra atrás das costas', 'Antebraço', '/exercicios/rosca-de-punho-com-barra-atras-das-costas.gif'),
  ('Rosca de punho com barra', 'Antebraço', '/exercicios/rosca-de-punho-com-barra.gif'),
  ('Rosca de punho pegada neutra com anilhas', 'Antebraço', '/exercicios/rosca-de-punho-pegada-neutra-com-anilhas.gif'),
  ('Rosca de punho reversa com barra', 'Antebraço', '/exercicios/rosca-de-punho-reversa-com-barra.gif'),
  ('Rosca inversa com barra', 'Antebraço', '/exercicios/rosca-inversa-com-barra.gif'),
  ('Máquina de rosca direta', 'Bíceps', '/exercicios/maquina-de-rosca-direta.gif'),
  ('Rosca alternada com barra', 'Bíceps', '/exercicios/rosca-alternada-com-barra.gif'),
  ('Rosca alternada com halteres sentado', 'Bíceps', '/exercicios/rosca-alternada-com-halteres-sentado.gif'),
  ('Rosca banco inclinado', 'Bíceps', '/exercicios/rosca-banco-inclinado.gif'),
  ('Rosca bilateral com cabo em banco inclinado', 'Bíceps', '/exercicios/rosca-bilateral-com-cabo-em-banco-inclinado.gif'),
  ('Rosca bíceps alta com halteres', 'Bíceps', '/exercicios/rosca-biceps-alta-com-halteres.gif'),
  ('Rosca bíceps com cabo ajoelhado', 'Bíceps', '/exercicios/rosca-biceps-com-cabo-ajoelhado.gif'),
  ('Rosca bíceps com halteres', 'Bíceps', '/exercicios/rosca-biceps-com-halteres.gif'),
  ('Rosca bíceps com pegada fechada na barra w', 'Bíceps', '/exercicios/rosca-biceps-com-pegada-fechada-na-barra-w.gif'),
  ('Rosca bíceps inclinada com cabos', 'Bíceps', '/exercicios/rosca-biceps-inclinada-com-cabos.gif'),
  ('Rosca bíceps inclinada com halteres sentado', 'Bíceps', '/exercicios/rosca-biceps-inclinada-com-halteres-sentado.gif'),
  ('Rosca bíceps sentado', 'Bíceps', '/exercicios/rosca-biceps-sentado.gif'),
  ('Rosca bíceps unilateral com pegada invertida em cabo', 'Bíceps', '/exercicios/rosca-biceps-unilateral-com-pegada-invertida-em-cabo.gif'),
  ('Rosca bíceps unilateral no cabo alto', 'Bíceps', '/exercicios/rosca-biceps-unilateral-no-cabo-alto.gif'),
  ('Rosca bíceps unilateral', 'Bíceps', '/exercicios/rosca-biceps-unilateral.gif'),
  ('Rosca com barra', 'Bíceps', '/exercicios/rosca-com-barra.gif'),
  ('Rosca com cabo de um braço', 'Bíceps', '/exercicios/rosca-com-cabo-de-um-braco.gif'),
  ('Rosca com halteres no colete scott', 'Bíceps', '/exercicios/rosca-com-halteres-no-colete-scott.gif'),
  ('Rosca com halteres', 'Bíceps', '/exercicios/rosca-com-halteres.gif'),
  ('Rosca com polia alta', 'Bíceps', '/exercicios/rosca-com-polia-alta.gif'),
  ('Rosca concentrada com cabo', 'Bíceps', '/exercicios/rosca-concentrada-com-cabo.gif'),
  ('Rosca concentrada com pegada fechada sentado', 'Bíceps', '/exercicios/rosca-concentrada-com-pegada-fechada-sentado.gif'),
  ('Rosca concentrada unilateral com cabo', 'Bíceps', '/exercicios/rosca-concentrada-unilateral-com-cabo.gif'),
  ('Rosca concentrada', 'Bíceps', '/exercicios/rosca-concentrada.gif'),
  ('Rosca de bíceps com alavanca', 'Bíceps', '/exercicios/rosca-de-biceps-com-alavanca.gif'),
  ('Rosca de bíceps com halteres no banco scott', 'Bíceps', '/exercicios/rosca-de-biceps-com-halteres-no-banco-scott.gif'),
  ('Rosca de bíceps com puxada de cabo', 'Bíceps', '/exercicios/rosca-de-biceps-com-puxada-de-cabo.gif'),
  ('Rosca direta com barra deitado em banco alto', 'Bíceps', '/exercicios/rosca-direta-com-barra-deitado-em-banco-alto.gif'),
  ('Rosca direta com barra em pegada fechada', 'Bíceps', '/exercicios/rosca-direta-com-barra-em-pegada-fechada.gif'),
  ('Rosca direta com barra no colete scott', 'Bíceps', '/exercicios/rosca-direta-com-barra-no-colete-scott.gif'),
  ('Rosca direta com barra w', 'Bíceps', '/exercicios/rosca-direta-com-barra-w.gif'),
  ('Rosca direta com barra', 'Bíceps', '/exercicios/rosca-direta-com-barra.gif'),
  ('Rosca direta com cabo deitado', 'Bíceps', '/exercicios/rosca-direta-com-cabo-deitado.gif'),
  ('Rosca inversa com barra w', 'Bíceps', '/exercicios/rosca-inversa-com-barra-w.gif'),
  ('Rosca inversa com halteres', 'Bíceps', '/exercicios/rosca-inversa-com-halteres.gif'),
  ('Rosca martelo com corda', 'Bíceps', '/exercicios/rosca-martelo-com-corda.gif'),
  ('Rosca martelo com halter no colete scott', 'Bíceps', '/exercicios/rosca-martelo-com-halter-no-colete-scott.gif'),
  ('Rosca martelo com halteres no banco scott', 'Bíceps', '/exercicios/rosca-martelo-com-halteres-no-banco-scott.gif'),
  ('Rosca martelo sentada', 'Bíceps', '/exercicios/rosca-martelo-sentada.gif'),
  ('Rosca martelo', 'Bíceps', '/exercicios/rosca-martelo.gif'),
  ('Rosca no cabo', 'Bíceps', '/exercicios/rosca-no-cabo.gif'),
  ('Rosca pronada no banco inclinado', 'Bíceps', '/exercicios/rosca-pronada-no-banco-inclinado.gif'),
  ('Rosca scott alternados com halteres', 'Bíceps', '/exercicios/rosca-scott-alternados-com-halteres.gif'),
  ('Rosca scott com alavanca', 'Bíceps', '/exercicios/rosca-scott-com-alavanca.gif'),
  ('Rosca scott com barra w', 'Bíceps', '/exercicios/rosca-scott-com-barra-w.gif'),
  ('Rosca scott com halteres martelo no banco', 'Bíceps', '/exercicios/rosca-scott-com-halteres-martelo-no-banco.gif'),
  ('Rosca scott com halteres', 'Bíceps', '/exercicios/rosca-scott-com-halteres.gif'),
  ('Rosca scott unilateral com halteres', 'Bíceps', '/exercicios/rosca-scott-unilateral-com-halteres.gif'),
  ('Rosca spider com único haltere', 'Bíceps', '/exercicios/rosca-spider-com-unico-haltere.gif'),
  ('Rosca spider unilateral', 'Bíceps', '/exercicios/rosca-spider-unilateral.gif'),
  ('Rosca unilateral com cabo', 'Bíceps', '/exercicios/rosca-unilateral-com-cabo.gif'),
  ('Rosca zottman', 'Bíceps', '/exercicios/rosca-zottman.gif'),
  ('Afundo no banco', 'Calistenia', '/exercicios/afundo-no-banco.gif'),
  ('Afundo profundo', 'Calistenia', '/exercicios/afundo-profundo.gif'),
  ('Afundo', 'Calistenia', '/exercicios/afundo.gif'),
  ('Agachamento búlgaro calistenia', 'Calistenia', '/exercicios/agachamento-bulgaro-calistenia.gif'),
  ('Agachamento búlgaro com salto', 'Calistenia', '/exercicios/agachamento-bulgaro-com-salto.gif'),
  ('Agachamento camarão', 'Calistenia', '/exercicios/agachamento-camarao.gif'),
  ('Agachamento com joelho elevado', 'Calistenia', '/exercicios/agachamento-com-joelho-elevado.gif'),
  ('Agachamento com salto', 'Calistenia', '/exercicios/agachamento-com-salto.gif'),
  ('Agachamento com sustentação e elevação de panturrilhas', 'Calistenia', '/exercicios/agachamento-com-sustentacao-e-elevacao-de-panturrilhas.gif'),
  ('Agachamento havaiano', 'Calistenia', '/exercicios/agachamento-havaiano.gif'),
  ('Agachamento no banco com peso corporal', 'Calistenia', '/exercicios/agachamento-no-banco-com-peso-corporal.gif'),
  ('Agachamento pistol com trx', 'Calistenia', '/exercicios/agachamento-pistol-com-trx.gif'),
  ('Agachamento pistola apoiado', 'Calistenia', '/exercicios/agachamento-pistola-apoiado.gif'),
  ('Agachamento pistola com kettlebell', 'Calistenia', '/exercicios/agachamento-pistola-com-kettlebell.gif'),
  ('Agachamento pistola na caixa', 'Calistenia', '/exercicios/agachamento-pistola-na-caixa.gif'),
  ('Agachamento pistola', 'Calistenia', '/exercicios/agachamento-pistola.gif'),
  ('Agachamento sissy ajoelhado com peso corporal', 'Calistenia', '/exercicios/agachamento-sissy-ajoelhado-com-peso-corporal.gif'),
  ('Agachamento skater', 'Calistenia', '/exercicios/agachamento-skater.gif'),
  ('Agachamento sumô sem pesos', 'Calistenia', '/exercicios/agachamento-sumo-sem-pesos.gif'),
  ('Agachamento', 'Calistenia', '/exercicios/agachamento.gif'),
  ('Alongamento do peitoral reverso', 'Calistenia', '/exercicios/alongamento-do-peitoral-reverso.gif'),
  ('Andar de pato', 'Calistenia', '/exercicios/andar-de-pato.gif'),
  ('Avanço sem peso corporal', 'Calistenia', '/exercicios/avanco-sem-peso-corporal.gif'),
  ('Back lever', 'Calistenia', '/exercicios/back-lever.gif'),
  ('Bandeira humana', 'Calistenia', '/exercicios/bandeira-humana.gif'),
  ('Barra fixa assistida com faixa elástica', 'Calistenia', '/exercicios/barra-fixa-assistida-com-faixa-elastica.gif'),
  ('Barra fixa com arco', 'Calistenia', '/exercicios/barra-fixa-com-arco.gif'),
  ('Barra fixa com braços alternados', 'Calistenia', '/exercicios/barra-fixa-com-bracos-alternados.gif'),
  ('Barra fixa com giro', 'Calistenia', '/exercicios/barra-fixa-com-giro.gif'),
  ('Barra fixa com l-sit', 'Calistenia', '/exercicios/barra-fixa-com-l-sit.gif'),
  ('Barra fixa com pegada fechada', 'Calistenia', '/exercicios/barra-fixa-com-pegada-fechada.gif'),
  ('Barra fixa com pegada invertida assistido', 'Calistenia', '/exercicios/barra-fixa-com-pegada-invertida-assistido.gif'),
  ('Barra fixa com pegada neutra', 'Calistenia', '/exercicios/barra-fixa-com-pegada-neutra.gif'),
  ('Barra fixa com pegada por trás do pescoço', 'Calistenia', '/exercicios/barra-fixa-com-pegada-por-tras-do-pescoco.gif'),
  ('Barra fixa com pegada supinada', 'Calistenia', '/exercicios/barra-fixa-com-pegada-supinada.gif'),
  ('Barra fixa com peso', 'Calistenia', '/exercicios/barra-fixa-com-peso.gif'),
  ('Barra fixa com salto', 'Calistenia', '/exercicios/barra-fixa-com-salto.gif'),
  ('Barra fixa de cabeça para baixo', 'Calistenia', '/exercicios/barra-fixa-de-cabeca-para-baixo.gif'),
  ('Barra fixa para o braquial', 'Calistenia', '/exercicios/barra-fixa-para-o-braquial.gif'),
  ('Barra fixa pegada invertida', 'Calistenia', '/exercicios/barra-fixa-pegada-invertida.gif'),
  ('Caminhada na parada de mão', 'Calistenia', '/exercicios/caminhada-na-parada-de-mao.gif'),
  ('Crucifixo com trx', 'Calistenia', '/exercicios/crucifixo-com-trx.gif'),
  ('Dips na cadeira', 'Calistenia', '/exercicios/dips-na-cadeira.gif'),
  ('Elevação de panturrilha em pé', 'Calistenia', '/exercicios/elevacao-de-panturrilha-em-pe.gif'),
  ('Elevação de panturrilha em uma perna', 'Calistenia', '/exercicios/elevacao-de-panturrilha-em-uma-perna.gif'),
  ('Elevação de quadril com peso corporal', 'Calistenia', '/exercicios/elevacao-de-quadril-com-peso-corporal.gif'),
  ('Elevação lateral com toalha na parede', 'Calistenia', '/exercicios/elevacao-lateral-com-toalha-na-parede.gif'),
  ('Elevação pélvica declinado', 'Calistenia', '/exercicios/elevacao-pelvica-declinado.gif'),
  ('Elevações de ombros na paralela', 'Calistenia', '/exercicios/elevacoes-de-ombros-na-paralela.gif'),
  ('Extensão de tríceps', 'Calistenia', '/exercicios/extensao-de-triceps.gif'),
  ('Flexão com barras de apoio', 'Calistenia', '/exercicios/flexao-com-barras-de-apoio.gif'),
  ('Flexão com cruzamento dos braços', 'Calistenia', '/exercicios/flexao-com-cruzamento-dos-bracos.gif'),
  ('Flexão com kettlebell profunda', 'Calistenia', '/exercicios/flexao-com-kettlebell-profunda.gif'),
  ('Flexão com parada de mãos', 'Calistenia', '/exercicios/flexao-com-parada-de-maos.gif'),
  ('Flexão com peso', 'Calistenia', '/exercicios/flexao-com-peso.gif'),
  ('Flexão com toque no peito', 'Calistenia', '/exercicios/flexao-com-toque-no-peito.gif'),
  ('Flexão com toque nos dedos dos pés', 'Calistenia', '/exercicios/flexao-com-toque-nos-dedos-dos-pes.gif'),
  ('Flexão com um braço', 'Calistenia', '/exercicios/flexao-com-um-braco.gif'),
  ('Flexão de braço com adução da escapula', 'Calistenia', '/exercicios/flexao-de-braco-com-aducao-da-escapula.gif'),
  ('Flexão de braço com arqueamento', 'Calistenia', '/exercicios/flexao-de-braco-com-arqueamento.gif'),
  ('Flexão de braço com bola de estabilidade', 'Calistenia', '/exercicios/flexao-de-braco-com-bola-de-estabilidade.gif'),
  ('Flexão de braço com bola medicinal com apoio em um braço', 'Calistenia', '/exercicios/flexao-de-braco-com-bola-medicinal-com-apoio-em-um-braco.gif'),
  ('Flexão de braço com palmas', 'Calistenia', '/exercicios/flexao-de-braco-com-palmas.gif'),
  ('Flexão de braço com uma perna', 'Calistenia', '/exercicios/flexao-de-braco-com-uma-perna.gif'),
  ('Flexão de braço declinada com bola de estabilidade', 'Calistenia', '/exercicios/flexao-de-braco-declinada-com-bola-de-estabilidade.gif'),
  ('Flexão de braço na parede com pegada fechada', 'Calistenia', '/exercicios/flexao-de-braco-na-parede-com-pegada-fechada.gif'),
  ('Flexão de braços com apoio dos joelhos fechada', 'Calistenia', '/exercicios/flexao-de-bracos-com-apoio-dos-joelhos-fechada.gif'),
  ('Flexão de braços com toque no ombro', 'Calistenia', '/exercicios/flexao-de-bracos-com-toque-no-ombro.gif'),
  ('Flexão de cotovelos na barra', 'Calistenia', '/exercicios/flexao-de-cotovelos-na-barra.gif'),
  ('Flexão de dedos', 'Calistenia', '/exercicios/flexao-de-dedos.gif'),
  ('Flexão de diamante de joelhos', 'Calistenia', '/exercicios/flexao-de-diamante-de-joelhos.gif'),
  ('Flexão de joelhos', 'Calistenia', '/exercicios/flexao-de-joelhos.gif'),
  ('Flexão de parede', 'Calistenia', '/exercicios/flexao-de-parede.gif'),
  ('Flexão de peito com trx', 'Calistenia', '/exercicios/flexao-de-peito-com-trx.gif'),
  ('Flexão de perna com halteres em decúbito dorsal', 'Calistenia', '/exercicios/flexao-de-perna-com-halteres-em-decubito-dorsal.gif'),
  ('Flexão de pernas com toalha', 'Calistenia', '/exercicios/flexao-de-pernas-com-toalha.gif'),
  ('Flexão de pivô com banco', 'Calistenia', '/exercicios/flexao-de-pivo-com-banco.gif'),
  ('Flexão de pivô entre cadeiras', 'Calistenia', '/exercicios/flexao-de-pivo-entre-cadeiras.gif'),
  ('Flexão de punho fechado', 'Calistenia', '/exercicios/flexao-de-punho-fechado.gif'),
  ('Flexão de queda', 'Calistenia', '/exercicios/flexao-de-queda.gif'),
  ('Flexão de um braço com apoio', 'Calistenia', '/exercicios/flexao-de-um-braco-com-apoio.gif'),
  ('Flexão de um braço com bola medicinal', 'Calistenia', '/exercicios/flexao-de-um-braco-com-bola-medicinal.gif'),
  ('Flexão declinada', 'Calistenia', '/exercicios/flexao-declinada.gif'),
  ('Flexão diamante', 'Calistenia', '/exercicios/flexao-diamante.gif'),
  ('Flexão em pivô', 'Calistenia', '/exercicios/flexao-em-pivo.gif'),
  ('Flexão fechada com bola medicinal', 'Calistenia', '/exercicios/flexao-fechada-com-bola-medicinal.gif'),
  ('Flexão hindu modificada', 'Calistenia', '/exercicios/flexao-hindu-modificada.gif'),
  ('Flexão inclinada', 'Calistenia', '/exercicios/flexao-inclinada.gif'),
  ('Flexão invertida', 'Calistenia', '/exercicios/flexao-invertida.gif'),
  ('Flexão na parede', 'Calistenia', '/exercicios/flexao-na-parede.gif'),
  ('Flexão plus', 'Calistenia', '/exercicios/flexao-plus.gif'),
  ('Flexão reversa com cotovelos', 'Calistenia', '/exercicios/flexao-reversa-com-cotovelos.gif'),
  ('Flexão', 'Calistenia', '/exercicios/flexao.gif'),
  ('Flexões de apoio de mão na parede', 'Calistenia', '/exercicios/flexoes-de-apoio-de-mao-na-parede.gif'),
  ('Flexões hindu', 'Calistenia', '/exercicios/flexoes-hindu.gif'),
  ('Impossible dips', 'Calistenia', '/exercicios/impossible-dips.gif'),
  ('Levantamento de panturrilha com apoio e sobrecarga', 'Calistenia', '/exercicios/levantamento-de-panturrilha-com-apoio-e-sobrecarga.gif'),
  ('Levantamento terra unilateral', 'Calistenia', '/exercicios/levantamento-terra-unilateral.gif'),
  ('Mergulho coreano', 'Calistenia', '/exercicios/mergulho-coreano.gif'),
  ('Mergulho de tríceps', 'Calistenia', '/exercicios/mergulho-de-triceps.gif'),
  ('Mergulhos para tríceps no chão', 'Calistenia', '/exercicios/mergulhos-para-triceps-no-chao.gif'),
  ('Muscle up', 'Calistenia', '/exercicios/muscle-up.gif'),
  ('Paralela', 'Calistenia', '/exercicios/paralela.gif'),
  ('Paralelas entre cadeiras', 'Calistenia', '/exercicios/paralelas-entre-cadeiras.gif'),
  ('Paralelas na argola', 'Calistenia', '/exercicios/paralelas-na-argola.gif'),
  ('Paralelas na barra', 'Calistenia', '/exercicios/paralelas-na-barra.gif'),
  ('Planche com flexão de braço', 'Calistenia', '/exercicios/planche-com-flexao-de-braco.gif'),
  ('Planche', 'Calistenia', '/exercicios/planche.gif'),
  ('Ponte em unilateral', 'Calistenia', '/exercicios/ponte-em-unilateral.gif'),
  ('Pulo de impulso de quadril de uma perna', 'Calistenia', '/exercicios/pulo-de-impulso-de-quadril-de-uma-perna.gif'),
  ('Puxada escapular na barra fixa', 'Calistenia', '/exercicios/puxada-escapular-na-barra-fixa.gif'),
  ('Puxada front lever', 'Calistenia', '/exercicios/puxada-front-lever.gif'),
  ('Puxada isométrica', 'Calistenia', '/exercicios/puxada-isometrica.gif'),
  ('Remada com o peso do corpo na porta', 'Calistenia', '/exercicios/remada-com-o-peso-do-corpo-na-porta.gif'),
  ('Remada invertida com argolas', 'Calistenia', '/exercicios/remada-invertida-com-argolas.gif'),
  ('Remada invertida na mesa', 'Calistenia', '/exercicios/remada-invertida-na-mesa.gif'),
  ('Rosca concentrada com perna', 'Calistenia', '/exercicios/rosca-concentrada-com-perna.gif'),
  ('Salto em caixa com uma perna', 'Calistenia', '/exercicios/salto-em-caixa-com-uma-perna.gif'),
  ('Salto em distância', 'Calistenia', '/exercicios/salto-em-distancia.gif'),
  ('Salto na caixa para agachamento pistola', 'Calistenia', '/exercicios/salto-na-caixa-para-agachamento-pistola.gif'),
  ('Salto para caixa 2 para 1', 'Calistenia', '/exercicios/salto-para-caixa-2-para-1.gif'),
  ('Suspensão passiva', 'Calistenia', '/exercicios/suspensao-passiva.gif'),
  ('Swing 360', 'Calistenia', '/exercicios/swing-360.gif'),
  ('Airbike', 'Cardio', '/exercicios/airbike.gif'),
  ('Bicicleta ergométrica reclinada', 'Cardio', '/exercicios/bicicleta-ergometrica-reclinada.gif'),
  ('Bike', 'Cardio', '/exercicios/bike.gif'),
  ('Corrida na bicicleta ergométrica', 'Cardio', '/exercicios/corrida-na-bicicleta-ergometrica.gif'),
  ('Esteira com inclinação', 'Cardio', '/exercicios/esteira-com-inclinacao.gif'),
  ('Esteira ergométrica', 'Cardio', '/exercicios/esteira-ergometrica.gif'),
  ('Hands bike', 'Cardio', '/exercicios/hands-bike.gif'),
  ('Máquina de caminhada ondulatório', 'Cardio', '/exercicios/maquina-de-caminhada-ondulatorio.gif'),
  ('Máquina elíptica', 'Cardio', '/exercicios/maquina-eliptica.gif'),
  ('Máquina simulador escada', 'Cardio', '/exercicios/maquina-simulador-escada.gif'),
  ('Plataforma vibratória', 'Cardio', '/exercicios/plataforma-vibratoria.gif'),
  ('Barra fixa assistida', 'Costas', '/exercicios/barra-fixa-assistida.gif'),
  ('Barra fixa', 'Costas', '/exercicios/barra-fixa.gif'),
  ('Levantamento terra romeno', 'Costas', '/exercicios/levantamento-terra-romeno.gif'),
  ('Levantamento terra', 'Costas', '/exercicios/levantamento-terra.gif'),
  ('Máquina de remo', 'Costas', '/exercicios/maquina-de-remo.gif'),
  ('Pull up', 'Costas', '/exercicios/pull-up.gif'),
  ('Pulldown com corda', 'Costas', '/exercicios/pulldown-com-corda.gif'),
  ('Pulldown inclinado com corda', 'Costas', '/exercicios/pulldown-inclinado-com-corda.gif'),
  ('Pulldown unilateral no cabo', 'Costas', '/exercicios/pulldown-unilateral-no-cabo.gif'),
  ('Pullover com barra no banco declinado', 'Costas', '/exercicios/pullover-com-barra-no-banco-declinado.gif'),
  ('Pullover com barra w pegada invertida', 'Costas', '/exercicios/pullover-com-barra-w-pegada-invertida.gif'),
  ('Pullover com barra', 'Costas', '/exercicios/pullover-com-barra.gif'),
  ('Pullover com cabo', 'Costas', '/exercicios/pullover-com-cabo.gif'),
  ('Puxada alta com alavanca', 'Costas', '/exercicios/puxada-alta-com-alavanca.gif'),
  ('Puxada alta com triângulo', 'Costas', '/exercicios/puxada-alta-com-triangulo.gif'),
  ('Puxada alta com um joelho apoiado', 'Costas', '/exercicios/puxada-alta-com-um-joelho-apoiado.gif'),
  ('Puxada alta invertida', 'Costas', '/exercicios/puxada-alta-invertida.gif'),
  ('Puxada alta na máquina nuca', 'Costas', '/exercicios/puxada-alta-na-maquina-nuca.gif'),
  ('Puxada alta na polia nuca', 'Costas', '/exercicios/puxada-alta-na-polia-nuca.gif'),
  ('Puxada alta neutra com cabos duplos no chão', 'Costas', '/exercicios/puxada-alta-neutra-com-cabos-duplos-no-chao.gif'),
  ('Puxada alta unilateral alta ajoelhada', 'Costas', '/exercicios/puxada-alta-unilateral-alta-ajoelhada.gif'),
  ('Puxada alta', 'Costas', '/exercicios/puxada-alta.gif'),
  ('Puxada com um braço com cabo', 'Costas', '/exercicios/puxada-com-um-braco-com-cabo.gif'),
  ('Puxada com um braço com peso adicional', 'Costas', '/exercicios/puxada-com-um-braco-com-peso-adicional.gif'),
  ('Puxada em pé com torção no cabo', 'Costas', '/exercicios/puxada-em-pe-com-torcao-no-cabo.gif'),
  ('Puxada na polia alta com pegada fechada', 'Costas', '/exercicios/puxada-na-polia-alta-com-pegada-fechada.gif'),
  ('Remada com cabo sentada unilateral com torção', 'Costas', '/exercicios/remada-com-cabo-sentada-unilateral-com-torcao.gif'),
  ('Remada com halteres em posição prancha', 'Costas', '/exercicios/remada-com-halteres-em-posicao-prancha.gif'),
  ('Remada cruzada no cross', 'Costas', '/exercicios/remada-cruzada-no-cross.gif'),
  ('Remada curvada com barra de pegada alternada ampla com adução de escapula', 'Costas', '/exercicios/remada-curvada-com-barra-de-pegada-alternada-ampla-com-aducao-de-escapula.gif'),
  ('Remada curvada com barra', 'Costas', '/exercicios/remada-curvada-com-barra.gif'),
  ('Remada curvada com halteres com pegada invertida', 'Costas', '/exercicios/remada-curvada-com-halteres-com-pegada-invertida.gif'),
  ('Remada curvada com halteres', 'Costas', '/exercicios/remada-curvada-com-halteres.gif'),
  ('Remada curvada com kettlebell', 'Costas', '/exercicios/remada-curvada-com-kettlebell.gif'),
  ('Remada curvada com pegada invertida na barra', 'Costas', '/exercicios/remada-curvada-com-pegada-invertida-na-barra.gif'),
  ('Remada curvada em t', 'Costas', '/exercicios/remada-curvada-em-t.gif'),
  ('Remada curvada inclinada com barra', 'Costas', '/exercicios/remada-curvada-inclinada-com-barra.gif'),
  ('Remada curvada no smith', 'Costas', '/exercicios/remada-curvada-no-smith.gif'),
  ('Remada de espingarda', 'Costas', '/exercicios/remada-de-espingarda.gif'),
  ('Remada frontal com alavanca', 'Costas', '/exercicios/remada-frontal-com-alavanca.gif'),
  ('Remada inclinada com cabo', 'Costas', '/exercicios/remada-inclinada-com-cabo.gif'),
  ('Remada inclinada com pegada neutra com halteres', 'Costas', '/exercicios/remada-inclinada-com-pegada-neutra-com-halteres.gif'),
  ('Remada inclinada com pegada reversa com halteres', 'Costas', '/exercicios/remada-inclinada-com-pegada-reversa-com-halteres.gif'),
  ('Remada inclinada no banco com cabo', 'Costas', '/exercicios/remada-inclinada-no-banco-com-cabo.gif'),
  ('Remada invertida', 'Costas', '/exercicios/remada-invertida.gif'),
  ('Remada renegada com halteres', 'Costas', '/exercicios/remada-renegada-com-halteres.gif'),
  ('Remada sentada com anilhas', 'Costas', '/exercicios/remada-sentada-com-anilhas.gif'),
  ('Remada sentada com cabo', 'Costas', '/exercicios/remada-sentada-com-cabo.gif'),
  ('Remada sentada com corda na polia', 'Costas', '/exercicios/remada-sentada-com-corda-na-polia.gif'),
  ('Remada sentada na máquina', 'Costas', '/exercicios/remada-sentada-na-maquina.gif'),
  ('Remada sentado com cabo pegada fechada', 'Costas', '/exercicios/remada-sentado-com-cabo-pegada-fechada.gif'),
  ('Remada t com alavanca', 'Costas', '/exercicios/remada-t-com-alavanca.gif'),
  ('Remada t com landmine', 'Costas', '/exercicios/remada-t-com-landmine.gif'),
  ('Remada t invertida com alavanca', 'Costas', '/exercicios/remada-t-invertida-com-alavanca.gif'),
  ('Remada unilateral com barra landmine', 'Costas', '/exercicios/remada-unilateral-com-barra-landmine.gif'),
  ('Remada unilateral com barra', 'Costas', '/exercicios/remada-unilateral-com-barra.gif'),
  ('Remada unilateral com cabo', 'Costas', '/exercicios/remada-unilateral-com-cabo.gif'),
  ('Serrote', 'Costas', '/exercicios/serrote.gif'),
  ('Abdução de quadril com cabo', 'Glúteos', '/exercicios/abducao-de-quadril-com-cabo.gif'),
  ('Abdução de quadril com ponte', 'Glúteos', '/exercicios/abducao-de-quadril-com-ponte.gif'),
  ('Abdução lateral do quadril com alavanca', 'Glúteos', '/exercicios/abducao-lateral-do-quadril-com-alavanca.gif'),
  ('Agachamento na máquina abdutora', 'Glúteos', '/exercicios/agachamento-na-maquina-abdutora.gif'),
  ('Elevação pélvica com barra declinado', 'Glúteos', '/exercicios/elevacao-pelvica-com-barra-declinado.gif'),
  ('Elevação pélvica com barra', 'Glúteos', '/exercicios/elevacao-pelvica-com-barra.gif'),
  ('Elevação pélvica na máquina de extensão de pernas', 'Glúteos', '/exercicios/elevacao-pelvica-na-maquina-de-extensao-de-pernas.gif'),
  ('Elevação pélvica na máquina smith', 'Glúteos', '/exercicios/elevacao-pelvica-na-maquina-smith.gif'),
  ('Elevação pélvica na máquina', 'Glúteos', '/exercicios/elevacao-pelvica-na-maquina.gif'),
  ('Elevação pélvica unilateral com barra', 'Glúteos', '/exercicios/elevacao-pelvica-unilateral-com-barra.gif'),
  ('Extensão de perna na máquina smith reversa', 'Glúteos', '/exercicios/extensao-de-perna-na-maquina-smith-reversa.gif'),
  ('Extensão de quadril com cabo', 'Glúteos', '/exercicios/extensao-de-quadril-com-cabo.gif'),
  ('Extensão de quadril em pé com alavanca', 'Glúteos', '/exercicios/extensao-de-quadril-em-pe-com-alavanca.gif'),
  ('Gluteos coice nilateral polia baixa', 'Glúteos', '/exercicios/gluteos-coice-nilateral-polia-baixa.gif'),
  ('Glúteo coice na alavanca', 'Glúteos', '/exercicios/gluteo-coice-na-alavanca.gif'),
  ('Glúteo coice na máquina de extensão de pernas', 'Glúteos', '/exercicios/gluteo-coice-na-maquina-de-extensao-de-pernas.gif'),
  ('Glúteo coice na máquina', 'Glúteos', '/exercicios/gluteo-coice-na-maquina.gif'),
  ('Glúteo coice no smith', 'Glúteos', '/exercicios/gluteo-coice-no-smith.gif'),
  ('Glúteos na polia baixa', 'Glúteos', '/exercicios/gluteos-na-polia-baixa.gif'),
  ('Máquina de abdução de quadril', 'Glúteos', '/exercicios/maquina-de-abducao-de-quadril.gif'),
  ('Ponte com halteres', 'Glúteos', '/exercicios/ponte-com-halteres.gif'),
  ('Puxada de cabo ajoelhada', 'Glúteos', '/exercicios/puxada-de-cabo-ajoelhada.gif'),
  ('Quatro apoios', 'Glúteos', '/exercicios/quatro-apoios.gif'),
  ('Crucifixo inverso unilateral com cabo', 'Ombros', '/exercicios/crucifixo-inverso-unilateral-com-cabo.gif'),
  ('Círculos de braço com pesos', 'Ombros', '/exercicios/circulos-de-braco-com-pesos.gif'),
  ('Desenvolvimento arnold (metade)', 'Ombros', '/exercicios/desenvolvimento-arnold-metade.gif'),
  ('Desenvolvimento arnold com um braço', 'Ombros', '/exercicios/desenvolvimento-arnold-com-um-braco.gif'),
  ('Desenvolvimento arnold', 'Ombros', '/exercicios/desenvolvimento-arnold.gif'),
  ('Desenvolvimento cubano com halteres', 'Ombros', '/exercicios/desenvolvimento-cubano-com-halteres.gif'),
  ('Desenvolvimento cubano sentado com halteres', 'Ombros', '/exercicios/desenvolvimento-cubano-sentado-com-halteres.gif'),
  ('Desenvolvimento de ombro alternada em pé com halteres', 'Ombros', '/exercicios/desenvolvimento-de-ombro-alternada-em-pe-com-halteres.gif'),
  ('Desenvolvimento de ombro com barra sentado', 'Ombros', '/exercicios/desenvolvimento-de-ombro-com-barra-sentado.gif'),
  ('Desenvolvimento de ombro com cabo ajoelhado', 'Ombros', '/exercicios/desenvolvimento-de-ombro-com-cabo-ajoelhado.gif'),
  ('Desenvolvimento de ombro com cabo', 'Ombros', '/exercicios/desenvolvimento-de-ombro-com-cabo.gif'),
  ('Desenvolvimento de ombro com halteres em forma de w', 'Ombros', '/exercicios/desenvolvimento-de-ombro-com-halteres-em-forma-de-w.gif'),
  ('Desenvolvimento de ombro com halteres em z', 'Ombros', '/exercicios/desenvolvimento-de-ombro-com-halteres-em-z.gif'),
  ('Desenvolvimento de ombro deitado', 'Ombros', '/exercicios/desenvolvimento-de-ombro-deitado.gif'),
  ('Desenvolvimento de ombro na máquina (pegada martelo)', 'Ombros', '/exercicios/desenvolvimento-de-ombro-na-maquina-pegada-martelo.gif'),
  ('Desenvolvimento de ombro na máquina', 'Ombros', '/exercicios/desenvolvimento-de-ombro-na-maquina.gif'),
  ('Desenvolvimento de ombro no banco com halteres', 'Ombros', '/exercicios/desenvolvimento-de-ombro-no-banco-com-halteres.gif'),
  ('Desenvolvimento de ombro reversa na máquina', 'Ombros', '/exercicios/desenvolvimento-de-ombro-reversa-na-maquina.gif'),
  ('Desenvolvimento de ombro unilateral com halter', 'Ombros', '/exercicios/desenvolvimento-de-ombro-unilateral-com-halter.gif'),
  ('Desenvolvimento de ombros atrás da cabeça na máquina smith', 'Ombros', '/exercicios/desenvolvimento-de-ombros-atras-da-cabeca-na-maquina-smith.gif'),
  ('Desenvolvimento de ombros atrás do pescoço sentado', 'Ombros', '/exercicios/desenvolvimento-de-ombros-atras-do-pescoco-sentado.gif'),
  ('Desenvolvimento de ombros com barra w com pegada invertida', 'Ombros', '/exercicios/desenvolvimento-de-ombros-com-barra-w-com-pegada-invertida.gif'),
  ('Desenvolvimento de ombros com halteres em pé com pegada neutra', 'Ombros', '/exercicios/desenvolvimento-de-ombros-com-halteres-em-pe-com-pegada-neutra.gif'),
  ('Desenvolvimento de ombros com rotação alternada com halteres', 'Ombros', '/exercicios/desenvolvimento-de-ombros-com-rotacao-alternada-com-halteres.gif'),
  ('Desenvolvimento de ombros na máquina smith', 'Ombros', '/exercicios/desenvolvimento-de-ombros-na-maquina-smith.gif'),
  ('Desenvolvimento de ombros na máquina', 'Ombros', '/exercicios/desenvolvimento-de-ombros-na-maquina.gif'),
  ('Desenvolvimento militar com barra no chão ajoelhado', 'Ombros', '/exercicios/desenvolvimento-militar-com-barra-no-chao-ajoelhado.gif'),
  ('Desenvolvimento militar com barra', 'Ombros', '/exercicios/desenvolvimento-militar-com-barra.gif'),
  ('Desenvolvimento militar com pegada fechada', 'Ombros', '/exercicios/desenvolvimento-militar-com-pegada-fechada.gif'),
  ('Desenvolvimento militar de uma mão com kettlebell', 'Ombros', '/exercicios/desenvolvimento-militar-de-uma-mao-com-kettlebell.gif'),
  ('Desenvolvimento militar em pé na máquina smith', 'Ombros', '/exercicios/desenvolvimento-militar-em-pe-na-maquina-smith.gif'),
  ('Desenvolvimento militar inclinado com barra presa no chão', 'Ombros', '/exercicios/desenvolvimento-militar-inclinado-com-barra-presa-no-chao.gif'),
  ('Elevação frontal alternada com halteres', 'Ombros', '/exercicios/elevacao-frontal-alternada-com-halteres.gif'),
  ('Elevação frontal com barra girando', 'Ombros', '/exercicios/elevacao-frontal-com-barra-girando.gif'),
  ('Elevação frontal com barra w inclinada', 'Ombros', '/exercicios/elevacao-frontal-com-barra-w-inclinada.gif'),
  ('Elevação frontal com cabo duplo no cross', 'Ombros', '/exercicios/elevacao-frontal-com-cabo-duplo-no-cross.gif'),
  ('Elevação frontal com dois braços com halteres', 'Ombros', '/exercicios/elevacao-frontal-com-dois-bracos-com-halteres.gif'),
  ('Elevação frontal com halteres sentado', 'Ombros', '/exercicios/elevacao-frontal-com-halteres-sentado.gif'),
  ('Elevação frontal com halteres', 'Ombros', '/exercicios/elevacao-frontal-com-halteres.gif'),
  ('Elevação lateral alternada com halteres', 'Ombros', '/exercicios/elevacao-lateral-alternada-com-halteres.gif'),
  ('Elevação lateral com barra no chão', 'Ombros', '/exercicios/elevacao-lateral-com-barra-no-chao.gif'),
  ('Elevação lateral com braço flexionado', 'Ombros', '/exercicios/elevacao-lateral-com-braco-flexionado.gif'),
  ('Elevação lateral com halteres com apoio no peito', 'Ombros', '/exercicios/elevacao-lateral-com-halteres-com-apoio-no-peito.gif'),
  ('Elevação lateral com halteres para deltoides posteriores deitado', 'Ombros', '/exercicios/elevacao-lateral-com-halteres-para-deltoides-posteriores-deitado.gif'),
  ('Elevação lateral com halteres sentado', 'Ombros', '/exercicios/elevacao-lateral-com-halteres-sentado.gif'),
  ('Elevação lateral com tronco inclinado', 'Ombros', '/exercicios/elevacao-lateral-com-tronco-inclinado.gif'),
  ('Elevação lateral cruzada no crossover', 'Ombros', '/exercicios/elevacao-lateral-cruzada-no-crossover.gif'),
  ('Elevação lateral de braços com cabo', 'Ombros', '/exercicios/elevacao-lateral-de-bracos-com-cabo.gif'),
  ('Elevação lateral de braços com halteres', 'Ombros', '/exercicios/elevacao-lateral-de-bracos-com-halteres.gif'),
  ('Elevação lateral de halteres inclinada', 'Ombros', '/exercicios/elevacao-lateral-de-halteres-inclinada.gif'),
  ('Elevação lateral deitado', 'Ombros', '/exercicios/elevacao-lateral-deitado.gif'),
  ('Elevação lateral e frontal com halteres', 'Ombros', '/exercicios/elevacao-lateral-e-frontal-com-halteres.gif'),
  ('Elevação lateral na máquina', 'Ombros', '/exercicios/elevacao-lateral-na-maquina.gif'),
  ('Elevação lateral unilateral com cabo', 'Ombros', '/exercicios/elevacao-lateral-unilateral-com-cabo.gif'),
  ('Elevação lateral unilateral com haltere inclinado', 'Ombros', '/exercicios/elevacao-lateral-unilateral-com-haltere-inclinado.gif'),
  ('Elevação lateral unilateral com halteres', 'Ombros', '/exercicios/elevacao-lateral-unilateral-com-halteres.gif'),
  ('Elevação posterior unilateral com halteres em decúbito prono', 'Ombros', '/exercicios/elevacao-posterior-unilateral-com-halteres-em-decubito-prono.gif'),
  ('Elevações frontais com halteres apoiadas no peito', 'Ombros', '/exercicios/elevacoes-frontais-com-halteres-apoiadas-no-peito.gif'),
  ('Levantamento de halteres de 3 maneiras', 'Ombros', '/exercicios/levantamento-de-halteres-de-3-maneiras.gif'),
  ('Levantamento de halteres de 4 maneiras', 'Ombros', '/exercicios/levantamento-de-halteres-de-4-maneiras-2.gif'),
  ('Levantamento frontal alternado com haltere sentado', 'Ombros', '/exercicios/levantamento-frontal-alternado-com-haltere-sentado.gif'),
  ('Levantamento frontal com anilha', 'Ombros', '/exercicios/levantamento-frontal-com-anilha.gif'),
  ('Levantamento frontal com barra', 'Ombros', '/exercicios/levantamento-frontal-com-barra.gif'),
  ('Levantamento frontal de cabo com dois braços', 'Ombros', '/exercicios/levantamento-frontal-de-cabo-com-dois-bracos.gif'),
  ('Levantamento frontal unilateral com cabo', 'Ombros', '/exercicios/levantamento-frontal-unilateral-com-cabo.gif'),
  ('Máquina de elevação lateral', 'Ombros', '/exercicios/maquina-de-elevacao-lateral.gif'),
  ('Remada alta', 'Ombros', '/exercicios/remada-alta-1.gif'),
  ('Remada com halteres para a posterior de ombros', 'Ombros', '/exercicios/remada-com-halteres-para-a-posterior-de-ombros.gif'),
  ('Remada de deltoide posterior sentado com haltere', 'Ombros', '/exercicios/remada-de-deltoide-posterior-sentado-com-haltere.gif'),
  ('Remada inversa com cabos deitado', 'Ombros', '/exercicios/remada-inversa-com-cabos-deitado.gif'),
  ('Remada lateral com halteres sentado', 'Ombros', '/exercicios/remada-lateral-com-halteres-sentado.gif'),
  ('Voador invertido', 'Ombros', '/exercicios/voador-invertido.gif'),
  ('Voador para deltoides posterior com cabo', 'Ombros', '/exercicios/voador-para-deltoides-posterior-com-cabo.gif'),
  ('Elevação de panturrilha com barra em pé', 'Panturrilha', '/exercicios/elevacao-de-panturrilha-com-barra-em-pe.gif'),
  ('Elevação de panturrilha com uma perna na máquina hack', 'Panturrilha', '/exercicios/elevacao-de-panturrilha-com-uma-perna-na-maquina-hack.gif'),
  ('Elevação de panturrilha em máquina em pé', 'Panturrilha', '/exercicios/elevacao-de-panturrilha-em-maquina-em-pe.gif'),
  ('Elevação de panturrilha na máquina', 'Panturrilha', '/exercicios/elevacao-de-panturrilha-na-maquina.gif'),
  ('Elevação de panturrilha no leg press horizontal', 'Panturrilha', '/exercicios/elevacao-de-panturrilha-no-leg-press-horizontal.gif'),
  ('Elevação de panturrilha no leg press', 'Panturrilha', '/exercicios/elevacao-de-panturrilha-no-leg-press.gif'),
  ('Elevação de panturrilha no smith', 'Panturrilha', '/exercicios/elevacao-de-panturrilha-no-smith.gif'),
  ('Elevação de panturrilha sentado com alavanca', 'Panturrilha', '/exercicios/elevacao-de-panturrilha-sentado-com-alavanca.gif'),
  ('Elevação de panturrilha sentado com barra', 'Panturrilha', '/exercicios/elevacao-de-panturrilha-sentado-com-barra.gif'),
  ('Elevação de panturrilha sentado com peso', 'Panturrilha', '/exercicios/elevacao-de-panturrilha-sentado-com-peso.gif'),
  ('Elevação de panturrilhas no hack', 'Panturrilha', '/exercicios/elevacao-de-panturrilhas-no-hack.gif'),
  ('Elevação de panturrilhas', 'Panturrilha', '/exercicios/elevacao-de-panturrilhas.gif'),
  ('Elevação unilateral de panturrilha no leg press', 'Panturrilha', '/exercicios/elevacao-unilateral-de-panturrilha-no-leg-press.gif'),
  ('Levantamento de panturrilha com alavanca', 'Panturrilha', '/exercicios/levantamento-de-panturrilha-com-alavanca.gif'),
  ('Levantamento de panturrilha com apoio de banco', 'Panturrilha', '/exercicios/levantamento-de-panturrilha-com-apoio-de-banco.gif'),
  ('Levantamento de panturrilha com apoio de uma perna', 'Panturrilha', '/exercicios/levantamento-de-panturrilha-com-apoio-de-uma-perna.gif'),
  ('Panturrilha em pé no smith', 'Panturrilha', '/exercicios/panturrilha-em-pe-no-smith.gif'),
  ('Panturrilhas em pé', 'Panturrilha', '/exercicios/panturrilhas-em-pe.gif'),
  ('Anilha press', 'Peito', '/exercicios/anilha-press.gif'),
  ('Cross over polia alta', 'Peito', '/exercicios/cross-over-polia-alta.gif'),
  ('Cross over polia baixa', 'Peito', '/exercicios/cross-over-polia-baixa.gif'),
  ('Cross over polia media', 'Peito', '/exercicios/cross-over-polia-media.gif'),
  ('Crossover de peitoral superior com cabo', 'Peito', '/exercicios/crossover-de-peitoral-superior-com-cabo.gif'),
  ('Crossover na alavanca', 'Peito', '/exercicios/crossover-na-alavanca.gif'),
  ('Crossover unilateral com cabo', 'Peito', '/exercicios/crossover-unilateral-com-cabo.gif'),
  ('Crucifixo com cabo declinado', 'Peito', '/exercicios/crucifixo-com-cabo-declinado.gif'),
  ('Crucifixo com halteres declinado', 'Peito', '/exercicios/crucifixo-com-halteres-declinado.gif'),
  ('Crucifixo com halteres inclinado', 'Peito', '/exercicios/crucifixo-com-halteres-inclinado.gif'),
  ('Crucifixo com halteres', 'Peito', '/exercicios/crucifixo-com-halteres.gif'),
  ('Crucifixo deitado com cabo', 'Peito', '/exercicios/crucifixo-deitado-com-cabo.gif'),
  ('Crucifixo inclinado cross', 'Peito', '/exercicios/crucifixo-inclinado-cross.gif'),
  ('Crucifixo unilateral em declinado com cabo', 'Peito', '/exercicios/crucifixo-unilateral-em-declinado-com-cabo.gif'),
  ('Mergulho de peito assistido', 'Peito', '/exercicios/mergulho-de-peito-assistido.gif'),
  ('Máquina de voador de peito inclinado', 'Peito', '/exercicios/maquina-de-voador-de-peito-inclinado.gif'),
  ('Paralelas', 'Peito', '/exercicios/paralelas.gif'),
  ('Pullover com haltere', 'Peito', '/exercicios/pullover-com-haltere.gif'),
  ('Pullover com halteres na bola de estabilidade', 'Peito', '/exercicios/pullover-com-halteres-na-bola-de-estabilidade.gif'),
  ('Pullover de braço reto com halteres (joelhos a 90 graus)', 'Peito', '/exercicios/pullover-de-braco-reto-com-halteres-joelhos-a-90-graus.gif'),
  ('Supino alternado com halteres', 'Peito', '/exercicios/supino-alternado-com-halteres.gif'),
  ('Supino com alavanca', 'Peito', '/exercicios/supino-com-alavanca.gif'),
  ('Supino com banco inclinado no smith', 'Peito', '/exercicios/supino-com-banco-inclinado-no-smith.gif'),
  ('Supino com barra declinado', 'Peito', '/exercicios/supino-com-barra-declinado.gif'),
  ('Supino com barra no chão', 'Peito', '/exercicios/supino-com-barra-no-chao.gif'),
  ('Supino com cabo sentado', 'Peito', '/exercicios/supino-com-cabo-sentado.gif'),
  ('Supino com haltere pegada fechada', 'Peito', '/exercicios/supino-com-haltere-pegada-fechada.gif'),
  ('Supino com halteres com pegada fechada', 'Peito', '/exercicios/supino-com-halteres-com-pegada-fechada.gif'),
  ('Supino com halteres pegada invertida', 'Peito', '/exercicios/supino-com-halteres-pegada-invertida.gif'),
  ('Supino com halteres', 'Peito', '/exercicios/supino-com-halteres.gif'),
  ('Supino com kettlebell de um braço', 'Peito', '/exercicios/supino-com-kettlebell-de-um-braco.gif'),
  ('Supino com kettlebell no chão', 'Peito', '/exercicios/supino-com-kettlebell-no-chao.gif'),
  ('Supino com pegada aberta', 'Peito', '/exercicios/supino-com-pegada-aberta.gif'),
  ('Supino com pegada fechada sentado com cabo', 'Peito', '/exercicios/supino-com-pegada-fechada-sentado-com-cabo.gif'),
  ('Supino com pegada fechada', 'Peito', '/exercicios/supino-com-pegada-fechada.gif'),
  ('Supino declinada com alavanca', 'Peito', '/exercicios/supino-declinada-com-alavanca.gif'),
  ('Supino declinada na máquina', 'Peito', '/exercicios/supino-declinada-na-maquina.gif'),
  ('Supino declinado com halteres', 'Peito', '/exercicios/supino-declinado-com-halteres.gif'),
  ('Supino declinado na máquina smith', 'Peito', '/exercicios/supino-declinado-na-maquina-smith.gif'),
  ('Supino declinado pegada martelo', 'Peito', '/exercicios/supino-declinado-pegada-martelo.gif'),
  ('Supino declinado unilateral pegada martelo com haltere', 'Peito', '/exercicios/supino-declinado-unilateral-pegada-martelo-com-haltere.gif'),
  ('Supino inclinado com barra', 'Peito', '/exercicios/supino-inclinado-com-barra.gif'),
  ('Supino inclinado com cabo', 'Peito', '/exercicios/supino-inclinado-com-cabo.gif'),
  ('Supino inclinado com halteres e pegada fechada', 'Peito', '/exercicios/supino-inclinado-com-halteres-e-pegada-fechada.gif'),
  ('Supino inclinado com halteres e pegada invertida', 'Peito', '/exercicios/supino-inclinado-com-halteres-e-pegada-invertida.gif'),
  ('Supino inclinado com halteres em martelo', 'Peito', '/exercicios/supino-inclinado-com-halteres-em-martelo.gif'),
  ('Supino inclinado com halteres', 'Peito', '/exercicios/supino-inclinado-com-halteres.gif'),
  ('Supino inclinado com pegada fechada', 'Peito', '/exercicios/supino-inclinado-com-pegada-fechada.gif'),
  ('Supino inclinado na alavanca', 'Peito', '/exercicios/supino-inclinado-na-alavanca.gif'),
  ('Supino inclinado na máquina com pegada martelo', 'Peito', '/exercicios/supino-inclinado-na-maquina-com-pegada-martelo.gif'),
  ('Supino inclinado na máquina', 'Peito', '/exercicios/supino-inclinado-na-maquina.gif'),
  ('Supino invertido com pegada aberta', 'Peito', '/exercicios/supino-invertido-com-pegada-aberta.gif'),
  ('Supino na máquina para miolo do peitoral', 'Peito', '/exercicios/supino-na-maquina-para-miolo-do-peitoral.gif'),
  ('Supino na máquina smith', 'Peito', '/exercicios/supino-na-maquina-smith.gif'),
  ('Supino na máquina', 'Peito', '/exercicios/supino-na-maquina.gif'),
  ('Supino no banco inclinado 30 graus com pegada invertida', 'Peito', '/exercicios/supino-no-banco-inclinado-30-graus-com-pegada-invertida.gif'),
  ('Supino no smith com o triângulo', 'Peito', '/exercicios/supino-no-smith-com-o-triangulo.gif'),
  ('Supino pegada martelo', 'Peito', '/exercicios/supino-pegada-martelo.gif'),
  ('Supino reto em pé no cross over', 'Peito', '/exercicios/supino-reto-em-pe-no-cross-over.gif'),
  ('Supino reto na máquina', 'Peito', '/exercicios/supino-reto-na-maquina.gif'),
  ('Supino reto', 'Peito', '/exercicios/supino-reto.gif'),
  ('Supino unilateral com alavanca', 'Peito', '/exercicios/supino-unilateral-com-alavanca.gif'),
  ('Supino unilateral com halteres com pegada reversa', 'Peito', '/exercicios/supino-unilateral-com-halteres-com-pegada-reversa.gif'),
  ('Supino unilateral no cabo', 'Peito', '/exercicios/supino-unilateral-no-cabo.gif'),
  ('Voador com halteres para cima', 'Peito', '/exercicios/voador-com-halteres-para-cima.gif'),
  ('Voador na máquina', 'Peito', '/exercicios/voador-na-maquina.gif'),
  ('Voador no pec deck', 'Peito', '/exercicios/voador-no-pec-deck.gif'),
  ('Voador unilateral no solo com barra', 'Peito', '/exercicios/voador-unilateral-no-solo-com-barra.gif'),
  ('Adução do quadril com cabo', 'Adutores/Abdutores', '/exercicios/aducao-do-quadril-com-cabo.gif'),
  ('Adução do quadril lateral com alavanca', 'Adutores/Abdutores', '/exercicios/aducao-do-quadril-lateral-com-alavanca.gif'),
  ('Afundo com barra', 'Quadríceps', '/exercicios/afundo-com-barra.gif'),
  ('Afundo com halteres', 'Quadríceps', '/exercicios/afundo-com-halteres.gif'),
  ('Afundo com landmine', 'Quadríceps', '/exercicios/afundo-com-landmine.gif'),
  ('Afundo lateral com barra', 'Quadríceps', '/exercicios/afundo-lateral-com-barra.gif'),
  ('Afundo na máquina smith', 'Quadríceps', '/exercicios/afundo-na-maquina-smith.gif'),
  ('Afundo no banco com halteres', 'Quadríceps', '/exercicios/afundo-no-banco-com-halteres.gif'),
  ('Agachamento barra', 'Quadríceps', '/exercicios/agachamento-barra.gif'),
  ('Agachamento búlgaro com barra', 'Quadríceps', '/exercicios/agachamento-bulgaro-com-barra.gif'),
  ('Agachamento búlgaro com halteres', 'Quadríceps', '/exercicios/agachamento-bulgaro-com-halteres.gif'),
  ('Agachamento com cinto', 'Quadríceps', '/exercicios/agachamento-com-cinto.gif'),
  ('Agachamento com halteres no banco', 'Quadríceps', '/exercicios/agachamento-com-halteres-no-banco.gif'),
  ('Agachamento com kettlebell', 'Quadríceps', '/exercicios/agachamento-com-kettlebell.gif'),
  ('Agachamento com salto e halteres', 'Quadríceps', '/exercicios/agachamento-com-salto-e-halteres.gif'),
  ('Agachamento com trava', 'Quadríceps', '/exercicios/agachamento-com-trava.gif'),
  ('Agachamento em plié com halteres', 'Quadríceps', '/exercicios/agachamento-em-plie-com-halteres.gif'),
  ('Agachamento frontal com barra no banco', 'Quadríceps', '/exercicios/agachamento-frontal-com-barra-no-banco.gif'),
  ('Agachamento frontal com barra no smith', 'Quadríceps', '/exercicios/agachamento-frontal-com-barra-no-smith.gif'),
  ('Agachamento frontal com cabo', 'Quadríceps', '/exercicios/agachamento-frontal-com-cabo.gif'),
  ('Agachamento frontal com kettlebell', 'Quadríceps', '/exercicios/agachamento-frontal-com-kettlebell.gif'),
  ('Agachamento frontal com polia', 'Quadríceps', '/exercicios/agachamento-frontal-com-polia.gif'),
  ('Agachamento frontal', 'Quadríceps', '/exercicios/agachamento-frontal.gif'),
  ('Agachamento goblet com haltere', 'Quadríceps', '/exercicios/agachamento-goblet-com-haltere.gif'),
  ('Agachamento hack com barra', 'Quadríceps', '/exercicios/agachamento-hack-com-barra.gif'),
  ('Agachamento hack invertido', 'Quadríceps', '/exercicios/agachamento-hack-invertido.gif'),
  ('Agachamento jefferson', 'Quadríceps', '/exercicios/agachamento-jefferson.gif'),
  ('Agachamento na máquina hack', 'Quadríceps', '/exercicios/agachamento-na-maquina-hack.gif'),
  ('Agachamento no landmine', 'Quadríceps', '/exercicios/agachamento-no-landmine.gif'),
  ('Agachamento no smith', 'Quadríceps', '/exercicios/agachamento-no-smith.gif'),
  ('Agachamento sissy', 'Quadríceps', '/exercicios/agachamento-sissy.gif'),
  ('Agachamento sumô com halteres', 'Quadríceps', '/exercicios/agachamento-sumo-com-halteres.gif'),
  ('Agachamento unilateral cruzado com barra', 'Quadríceps', '/exercicios/agachamento-unilateral-cruzado-com-barra.gif'),
  ('Agachamento unilateral cruzado com haltere', 'Quadríceps', '/exercicios/agachamento-unilateral-cruzado-com-haltere.gif'),
  ('Agachamento zercher', 'Quadríceps', '/exercicios/agachamento-zercher.gif'),
  ('Avanço com barra', 'Quadríceps', '/exercicios/avanco-com-barra.gif'),
  ('Avanço com cabo', 'Quadríceps', '/exercicios/avanco-com-cabo.gif'),
  ('Avanço com halteres para trás', 'Quadríceps', '/exercicios/avanco-com-halteres-para-tras.gif'),
  ('Avanço com halteres', 'Quadríceps', '/exercicios/avanco-com-halteres.gif'),
  ('Avanço com puxador de cabo', 'Quadríceps', '/exercicios/avanco-com-puxador-de-cabo.gif'),
  ('Avanço invertido com halteres', 'Quadríceps', '/exercicios/avanco-invertido-com-halteres.gif'),
  ('Avanço invertido', 'Quadríceps', '/exercicios/avanco-invertido.gif'),
  ('Bom dia na máquina smith', 'Posterior', '/exercicios/bom-dia-na-maquina-smith.gif'),
  ('Bom dia', 'Posterior', '/exercicios/bom-dia.gif'),
  ('Cadeira extensora', 'Quadríceps', '/exercicios/cadeira-extensora.gif'),
  ('Cadeira flexora', 'Posterior', '/exercicios/cadeira-flexora.gif'),
  ('Descida de um pé só', 'Quadríceps', '/exercicios/descida-de-um-pe-so.gif'),
  ('Elevação com barra em degrau', 'Quadríceps', '/exercicios/elevacao-com-barra-em-degrau.gif'),
  ('Elevação de joelho com halteres', 'Quadríceps', '/exercicios/elevacao-de-joelho-com-halteres.gif'),
  ('Elevação de perna em pé com alavanca', 'Quadríceps', '/exercicios/elevacao-de-perna-em-pe-com-alavanca.gif'),
  ('Extensão de perna unilateral', 'Quadríceps', '/exercicios/extensao-de-perna-unilateral.gif'),
  ('Flexão de pernas com alavanca', 'Posterior', '/exercicios/flexao-de-pernas-com-alavanca.gif'),
  ('Flexão de pernas com halteres declinado', 'Posterior', '/exercicios/flexao-de-pernas-com-halteres-declinado.gif'),
  ('Flexão nórdica', 'Posterior', '/exercicios/flexao-nordica.gif'),
  ('Leg press 90 no smith', 'Quadríceps', '/exercicios/leg-press-90-no-smith.gif'),
  ('Leg press horizontal', 'Quadríceps', '/exercicios/leg-press-horizontal.gif'),
  ('Leg press unilateral', 'Quadríceps', '/exercicios/leg-press-unilateral.gif'),
  ('Leg press', 'Quadríceps', '/exercicios/leg-press.gif'),
  ('Levantamento com suporte', 'Quadríceps', '/exercicios/levantamento-com-suporte.gif'),
  ('Levantamento terra com alavanca', 'Posterior', '/exercicios/levantamento-terra-com-alavanca.gif'),
  ('Levantamento terra com barra hexagonal', 'Posterior', '/exercicios/levantamento-terra-com-barra-hexagonal.gif'),
  ('Levantamento terra com barra no landmine', 'Posterior', '/exercicios/levantamento-terra-com-barra-no-landmine.gif'),
  ('Levantamento terra com halteres', 'Posterior', '/exercicios/levantamento-terra-com-halteres.gif'),
  ('Levantamento terra com kettlebell', 'Posterior', '/exercicios/levantamento-terra-com-kettlebell.gif'),
  ('Levantamento terra romeno com halteres', 'Posterior', '/exercicios/levantamento-terra-romeno-com-halteres.gif'),
  ('Levantamento terra sumô com halteres', 'Posterior', '/exercicios/levantamento-terra-sumo-com-halteres.gif'),
  ('Levantamento terra sumô', 'Posterior', '/exercicios/levantamento-terra-sumo.gif'),
  ('Levantamento terra zercher', 'Posterior', '/exercicios/levantamento-terra-zercher.gif'),
  ('Mesa flexora unilateral', 'Posterior', '/exercicios/mesa-flexora-unilateral.gif'),
  ('Mesa flexora', 'Posterior', '/exercicios/mesa-flexora.gif'),
  ('Máquina de adução de quadril', 'Adutores/Abdutores', '/exercicios/maquina-de-aducao-de-quadril.gif'),
  ('Máquina de flexão de perna unilateral', 'Posterior', '/exercicios/maquina-de-flexao-de-perna-unilateral.gif'),
  ('Peso muerto piernas rígidas con barra', 'Posterior', '/exercicios/peso-muerto-piernas-rigidas-con-barra.gif'),
  ('Ponte de glúteos com barra', 'Posterior', '/exercicios/ponte-de-gluteos-com-barra.gif'),
  ('Pressão unilateral assistida por alavanca', 'Quadríceps', '/exercicios/pressao-unilateral-assistida-por-alavanca.gif'),
  ('Stiff com barra', 'Posterior', '/exercicios/stiff-com-barra.gif'),
  ('Stiff com halter', 'Posterior', '/exercicios/stiff-com-halter.gif'),
  ('Stiff unilateral com barra', 'Posterior', '/exercicios/stiff-unilateral-com-barra.gif'),
  ('Stiff unilateral com halteres', 'Posterior', '/exercicios/stiff-unilateral-com-halteres.gif'),
  ('Dips de escápula', 'Trapézio', '/exercicios/dips-de-escapula.gif'),
  ('Dumbbell-raise', 'Trapézio', '/exercicios/dumbbell-raise.gif'),
  ('Elevação de deltoide em y com halteres inclinado', 'Trapézio', '/exercicios/elevacao-de-deltoide-em-y-com-halteres-inclinado.gif'),
  ('Elevação de deltoide posterior com halteres inclinado', 'Trapézio', '/exercicios/elevacao-de-deltoide-posterior-com-halteres-inclinado.gif'),
  ('Elevação de t com halteres inclinada', 'Trapézio', '/exercicios/elevacao-de-t-com-halteres-inclinada.gif'),
  ('Elevação lateral tronco inclinado', 'Trapézio', '/exercicios/elevacao-lateral-tronco-inclinado.gif'),
  ('Encolhimento acima da cabeça', 'Trapézio', '/exercicios/encolhimento-acima-da-cabeca.gif'),
  ('Encolhimento com alavanca', 'Trapézio', '/exercicios/encolhimento-com-alavanca.gif'),
  ('Encolhimento com cabo', 'Trapézio', '/exercicios/encolhimento-com-cabo.gif'),
  ('Encolhimento com halteres em declive', 'Trapézio', '/exercicios/encolhimento-com-halteres-em-declive.gif'),
  ('Encolhimento com halteres', 'Trapézio', '/exercicios/encolhimento-com-halteres.gif'),
  ('Encolhimento de barra atrás das costas', 'Trapézio', '/exercicios/encolhimento-de-barra-atras-das-costas.gif'),
  ('Encolhimento de barra', 'Trapézio', '/exercicios/encolhimento-de-barra.gif'),
  ('Encolhimento de ombros na máquina smith', 'Trapézio', '/exercicios/encolhimento-de-ombros-na-maquina-smith.gif'),
  ('Encolhimento de ombros por trás com barra', 'Trapézio', '/exercicios/encolhimento-de-ombros-por-tras-com-barra.gif'),
  ('Encolhimento inclinado pronado', 'Trapézio', '/exercicios/encolhimento-inclinado-pronado.gif'),
  ('Encolhimento na máquina', 'Trapézio', '/exercicios/encolhimento-na-maquina.gif'),
  ('Encolhimento sentado de gittleson com halteres', 'Trapézio', '/exercicios/encolhimento-sentado-de-gittleson-com-halteres.gif'),
  ('Face pull', 'Trapézio', '/exercicios/face-pull.gif'),
  ('Meio agachado com puxada para o rosto no cabo', 'Trapézio', '/exercicios/meio-agachado-com-puxada-para-o-rosto-no-cabo.gif'),
  ('Puxada de face com cabo cruzado', 'Trapézio', '/exercicios/puxada-de-face-com-cabo-cruzado.gif'),
  ('Puxada para o rosto de joelhos', 'Trapézio', '/exercicios/puxada-para-o-rosto-de-joelhos.gif'),
  ('Remada alta com barra w', 'Trapézio', '/exercicios/remada-alta-com-barra-w.gif'),
  ('Remada alta com cabo', 'Trapézio', '/exercicios/remada-alta-com-cabo.gif'),
  ('Remada alta com halter', 'Trapézio', '/exercicios/remada-alta-com-halter.gif'),
  ('Remada alta com halteres unilateral', 'Trapézio', '/exercicios/remada-alta-com-halteres-unilateral.gif'),
  ('Remada com barra', 'Trapézio', '/exercicios/remada-com-barra.gif'),
  ('Remada em y com cabo', 'Trapézio', '/exercicios/remada-em-y-com-cabo.gif'),
  ('Remada inclinada a 45 graus', 'Trapézio', '/exercicios/remada-inclinada-a-45-graus.gif'),
  ('Remada invertida com cable inclinado', 'Trapézio', '/exercicios/remada-invertida-com-cable-inclinado.gif'),
  ('Remada invertida com halteres inclinado', 'Trapézio', '/exercicios/remada-invertida-com-halteres-inclinado.gif'),
  ('Voador de deltoides posterior com cabo', 'Trapézio', '/exercicios/voador-de-deltoides-posterior-com-cabo.gif'),
  ('Voador na máquina para deltoides posteriores', 'Trapézio', '/exercicios/voador-na-maquina-para-deltoides-posteriores.gif'),
  ('Extensão concentrada com cabo no joelho', 'Tríceps', '/exercicios/extensao-concentrada-com-cabo-no-joelho.gif'),
  ('Extensão de tríceps com barra atrás da cabeça', 'Tríceps', '/exercicios/extensao-de-triceps-com-barra-atras-da-cabeca.gif'),
  ('Extensão de tríceps com barra em pé', 'Tríceps', '/exercicios/extensao-de-triceps-com-barra-em-pe.gif'),
  ('Extensão de tríceps com barra w inclinada', 'Tríceps', '/exercicios/extensao-de-triceps-com-barra-w-inclinada.gif'),
  ('Extensão de tríceps com cabo ajoelhado', 'Tríceps', '/exercicios/extensao-de-triceps-com-cabo-ajoelhado.gif'),
  ('Extensão de tríceps com cabo em posição ajoelhada', 'Tríceps', '/exercicios/extensao-de-triceps-com-cabo-em-posicao-ajoelhada.gif'),
  ('Extensão de tríceps com cabo inclinado', 'Tríceps', '/exercicios/extensao-de-triceps-com-cabo-inclinado.gif'),
  ('Extensão de tríceps com cabo na posição horizontal', 'Tríceps', '/exercicios/extensao-de-triceps-com-cabo-na-posicao-horizontal.gif'),
  ('Extensão de tríceps com cabos cruzados', 'Tríceps', '/exercicios/extensao-de-triceps-com-cabos-cruzados.gif'),
  ('Extensão de tríceps com deitado com barra', 'Tríceps', '/exercicios/extensao-de-triceps-com-deitado-com-barra.gif'),
  ('Extensão de tríceps com haltere em pronação com um braço', 'Tríceps', '/exercicios/extensao-de-triceps-com-haltere-em-pronacao-com-um-braco.gif'),
  ('Extensão de tríceps com haltere unilateral sentado', 'Tríceps', '/exercicios/extensao-de-triceps-com-haltere-unilateral-sentado.gif'),
  ('Extensão de tríceps com pegada invertida', 'Tríceps', '/exercicios/extensao-de-triceps-com-pegada-invertida.gif'),
  ('Extensão de tríceps com um braço', 'Tríceps', '/exercicios/extensao-de-triceps-com-um-braco.gif'),
  ('Extensão de tríceps com uma mão no pulley alto sobre a cabeça', 'Tríceps', '/exercicios/extensao-de-triceps-com-uma-mao-no-pulley-alto-sobre-a-cabeca.gif'),
  ('Extensão de tríceps deitado com barra w pegada fechada atrás da cabeça', 'Tríceps', '/exercicios/extensao-de-triceps-deitado-com-barra-w-pegada-fechada-atras-da-cabeca.gif'),
  ('Extensão de tríceps deitado com corda', 'Tríceps', '/exercicios/extensao-de-triceps-deitado-com-corda.gif'),
  ('Extensão de tríceps invertida com unilateral', 'Tríceps', '/exercicios/extensao-de-triceps-invertida-com-unilateral.gif'),
  ('Extensão de tríceps lateral com cabo', 'Tríceps', '/exercicios/extensao-de-triceps-lateral-com-cabo.gif'),
  ('Extensão de tríceps na máquina pegada neutra', 'Tríceps', '/exercicios/extensao-de-triceps-na-maquina-pegada-neutra.gif'),
  ('Extensão de tríceps na máquina', 'Tríceps', '/exercicios/extensao-de-triceps-na-maquina.gif'),
  ('Extensão de tríceps no cabo alto', 'Tríceps', '/exercicios/extensao-de-triceps-no-cabo-alto.gif'),
  ('Extensão de tríceps no cabo deitado', 'Tríceps', '/exercicios/extensao-de-triceps-no-cabo-deitado.gif'),
  ('Extensão de tríceps testa declinado fechado', 'Tríceps', '/exercicios/extensao-de-triceps-testa-declinado-fechado.gif'),
  ('Flexão de apoio com elevação de braço', 'Tríceps', '/exercicios/flexao-de-apoio-com-elevacao-de-braco.gif'),
  ('Mergulho de tríceps com alavanca', 'Tríceps', '/exercicios/mergulho-de-triceps-com-alavanca.gif'),
  ('Mergulhos assistidos para tríceps', 'Tríceps', '/exercicios/mergulhos-assistidos-para-triceps.gif'),
  ('Máquina de flexão de tríceps', 'Tríceps', '/exercicios/maquina-de-flexao-de-triceps.gif'),
  ('Supino fechado', 'Tríceps', '/exercicios/supino-fechado.gif'),
  ('Supino invertido com pegada fechada', 'Tríceps', '/exercicios/supino-invertido-com-pegada-fechada.gif'),
  ('Tríceps coice com cabo', 'Tríceps', '/exercicios/triceps-coice-com-cabo.gif'),
  ('Tríceps coice com halteres', 'Tríceps', '/exercicios/triceps-coice-com-halteres.gif'),
  ('Tríceps francês alternada com halteres no banco inclinado', 'Tríceps', '/exercicios/triceps-frances-alternada-com-halteres-no-banco-inclinado.gif'),
  ('Tríceps francês com barra w acima da cabeça sentado', 'Tríceps', '/exercicios/triceps-frances-com-barra-w-acima-da-cabeca-sentado.gif'),
  ('Tríceps francês com halter bilateral', 'Tríceps', '/exercicios/triceps-frances-com-halter-bilateral.gif'),
  ('Tríceps francês com halteres', 'Tríceps', '/exercicios/triceps-frances-com-halteres.gif'),
  ('Tríceps francês na polia com corda', 'Tríceps', '/exercicios/triceps-frances-na-polia-com-corda.gif'),
  ('Tríceps francês no banco inclinado com halter', 'Tríceps', '/exercicios/triceps-frances-no-banco-inclinado-com-halter.gif'),
  ('Tríceps francês unilateral no cabo', 'Tríceps', '/exercicios/triceps-frances-unilateral-no-cabo.gif'),
  ('Tríceps no banco(1)', 'Tríceps', '/exercicios/triceps-no-banco-1.gif'),
  ('Tríceps no banco', 'Tríceps', '/exercicios/triceps-no-banco.gif'),
  ('Tríceps pulley barra v', 'Tríceps', '/exercicios/triceps-pulley-barra-v.gif'),
  ('Tríceps pulley barra', 'Tríceps', '/exercicios/triceps-pulley-barra.gif'),
  ('Tríceps pulley corda', 'Tríceps', '/exercicios/triceps-pulley-corda.gif'),
  ('Tríceps pulley pegada invertida', 'Tríceps', '/exercicios/triceps-pulley-pegada-invertida.gif'),
  ('Tríceps testa com banco declinado com halteres', 'Tríceps', '/exercicios/triceps-testa-com-banco-declinado-com-halteres.gif'),
  ('Tríceps testa com barra pegada invertida', 'Tríceps', '/exercicios/triceps-testa-com-barra-pegada-invertida.gif'),
  ('Tríceps testa com barra', 'Tríceps', '/exercicios/triceps-testa-com-barra.gif'),
  ('Tríceps testa pegada neutra com halteres', 'Tríceps', '/exercicios/triceps-testa-pegada-neutra-com-halteres.gif');
